export const TEAM_TARGETS = {
  architect: {id:'Menjadi penanggung jawab arsitektur sampai rilis: pecah prioritas menjadi tugas per tim, catat dependensi/hambatan, dan susun keputusan go/no-go berdasarkan tes, review PR, deployment, smoke test, serta rencana rollback.',en:'Own architecture through release: split priorities into team tasks, track dependencies/blockers, and prepare go/no-go decisions based on tests, PR review, deployment, smoke tests, and rollback plans.'},
  research: {id:'Siapkan lima pertanyaan wawancara dan tiga hipotesis kebutuhan untuk pengguna dewasa; tetapkan ukuran keberhasilan, bedakan asumsi dari temuan, dan beri rekomendasi prioritas kepada Arsitek serta Marketing.',en:'Prepare five interview questions and three needs hypotheses for adult users; define success measures, distinguish assumptions from findings, and recommend priorities to Architecture and Marketing.'},
  backend: {id:'Menjaga chat dan sesi stabil; setiap perbaikan disertai tes dan bukti deployment.',en:'Keep chat and sessions stable; provide tests and deployment evidence for every fix.'},
  experience: {id:'Menyederhanakan sambutan menjadi tiga pilihan dan merancang mode Hening tanpa memaksa produktivitas.',en:'Simplify entry into three choices and design Quiet mode without pressure to be productive.'},
  audio: {id:'Memisahkan musik ceria dari mode kerja serta merancang transisi musik yang lembut.',en:'Separate cheerful music from work mode and design gentle music transitions.'},
  visual: {id:'Menjaga kantor dan ruang aktivitas jelas, responsif, serta nyaman digunakan di HP.',en:'Keep the office and activity rooms clear, responsive, and comfortable on mobile.'},
  scanner: {id:'Menyiapkan pengujian kamera, pencahayaan, dan wajah nyata tanpa klaim diagnosis emosi.',en:'Prepare real-camera, lighting, and face checks without emotion-diagnosis claims.'},
  qa: {id:'Memeriksa alur utama, aksesibilitas, error, dan HP; mencatat hasil lulus/gagal dengan bukti.',en:'Check key flows, accessibility, failures, and mobile; record pass/fail results with evidence.'},
  marketing: {id:'Memimpin segmentasi, positioning, dan rencana pilot 7 hari untuk 20–30 pengguna dewasa: siapkan kanal, pesan, metrik aktivasi/retensi dan batas biaya. Perekrutan dan kampanye belum dimulai.',en:'Lead segmentation, positioning, and a seven-day pilot plan for 20–30 adults: prepare channels, messages, activation/retention metrics, and budget limits. Recruitment and campaigns have not started.'},
  community: {id:'Merapikan onboarding kontributor dan daftar issue; tidak mengklaim sudah memiliki anggota aktif.',en:'Improve contributor onboarding and issues; do not claim active members without evidence.'},
};
